spring:
  application:
    name: backend-content
  rabbitmq:
      addresses: 192.168.130.146
      username: guest
      password: guest
      port: 5672
      virtual-host: /
server:
  port: 9021
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
tx-lcn:
  client:
    manager-address: 192.168.130.152:8070

