spring:
  application:
    name: common-redis
  rabbitmq:
      addresses: 192.168.130.146
      username: guest
      password: guest
      port: 5672
      virtual-host: /
  redis:
    host: 192.168.130.152
    database: 1
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
server:
  port: 9080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

#配置缓存首页商品分类的key
frontend_catresult_redis_key: frontend:catresult:redis:key
#配置缓存首页大广告位的key
frontend_ad_redis_key: frontend:ad:redis:key:89
#配置缓存商品基本信息的key
frontend_item_basic_info_key: frontend:item:basic:info:key
#配置缓存首页商品介绍的key
frontend_item_desc_key: frontend:item:desc:key
#配置缓存首页商品规格参数的key
frontend_item_param_item_key: frontend:item:param:item:key

#配置用户缓存key
user_session_redis_key: user:session:redis:key

#缓存用户购物车的根key
frontend_cart_redis_key: frontend:cart:redis:key

#缓存订单id的key
order_item_id_key: order:item:id:key
#订单id初始值
init_item_id: 2000



