spring:
  application:
    name: common-zuul
  rabbitmq:
      addresses: 192.168.130.146
      username: guest
      password: guest
      port: 5672
      virtual-host: /
server:
  port: 7070

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

zuul:
  sensitive-headers: true #全局配置，解决在网关服务中不传递请求头的问题(Cookie)
  routes:

    #后台商品服务路由规则
   backend-item:
    path: /backend_item/**
    #后台 CMS 服务的路由规则
   backend-content:
    path: /backend_content/**
  #前台首页服务的路由规则
   frontend-protal:
    path: /frontend_potal/**
  #前台搜索服务的路由规则
   frontend-search:
    path: /frontend_search/**
  #前台注册和登录服务的路由规则
   frontend-sso:
    path: /frontend_sso/**
  #前台订单服务的路由规则
   frontend-order:
    path: /frontend_order/**
  #前台购物车
   frontend-cart:
    path: /frontend_cart/**

#配置网关超时时间
#第一层hystrix的超时时间
hystrix:
 command:
  default:
   execution:
    isolation:
      thread:
        timeoutInMilliseconds: 5000
#第二层Ribbon超时时间
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 5000

