spring:
  application:
    name: frontend-cart
  rabbitmq:
      addresses: 192.168.130.146
      username: guest
      password: guest
      port: 5672
      virtual-host: /
server:
  port: 9040
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

cart_cookie_name: cart_cookie_name