spring:
  application:
    name: frontend-order
  rabbitmq:
      addresses: 192.168.130.146
      username: guest
      password: guest
      port: 5672
      virtual-host: /
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bz_shop?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 9111

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
#TX-LCN 服务端地址
tx-lcn:
  client:
    manager-address: 192.168.130.152:8070

