spring:
  application:
    name: frontend-search
  rabbitmq:
      addresses: 192.168.130.146
      username: guest
      password: guest
      port: 5672
      virtual-host: /
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bz_shop?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    solr:
      host: http://192.168.130.153:8080/solr
      core: collection1
server:
  port: 9100
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
