spring:
  application:
    name: frontend-protal
  rabbitmq:
      addresses: 192.168.130.146
      username: guest
      password: guest
      port: 5672
      virtual-host: /
server:
  port: 9030
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
